export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as People } from './People/People'
export { default as News } from './News/News'
export { default as Publications } from './Publications/Publications'
